// The renderer: listings in, Markdown out.
//
// Pure and clock-free (`now` is an argument), so the same input always produces
// the same bytes. That is what lets the workflow commit only when the LISTINGS
// changed rather than once an hour forever.
//
// ── The two shapes this file writes ──────────────────────────────────────────
//
//   * **The README block.** Everything between the two markers below; the prose
//     above and beneath them is hand-written and never touched, so a maintainer
//     can rewrite the intro, add a banner or fix a typo without the next run
//     reverting it.
//   * **A filter page.** A whole generated file under `lists/`, one per track —
//     Big Tech, Fintech, Machine Learning Engineer, SF Bay Area. These carry the
//     rows the README cannot.
//
// ── Why the README is capped ─────────────────────────────────────────────────
//
// **GitHub stops rendering a Markdown file at 512,000 bytes** and prints a
// truncation notice in place of the rest. The new-grad list crossed that line
// (554,638 bytes, ~1,500 rows) and the bottom third of the page was simply not
// being drawn — for a file nobody would think to check the byte count of. So
// the README is now an INDEX: the freshest roles in each field, a fold under
// each, and a link to the filter page that carries every row. `README_MAX_BYTES`
// is the backstop, and the per-section caps are what actually keep it there.

import { ageInDays, ageLabel, escapeHtml, escapeMarkdown, link, locationLabel, markers, postedLabel, safeUrl } from './format.mjs';
import { anchorOf, groupByCategory, splitByFreshness } from './select.mjs';
import { groupTracks } from './tracks.mjs';

export const BLOCK_START = '<!-- LISTINGS:START — everything between these markers is generated hourly. Edit the scripts, not the table. -->';
export const BLOCK_END = '<!-- LISTINGS:END -->';

/** GitHub renders at most this many bytes of a Markdown file. */
export const GITHUB_RENDER_LIMIT = 512_000;

/** Where a generated file has to stay, well under the limit rather than near it. */
export const README_MAX_BYTES = 400_000;
export const PAGE_MAX_BYTES = 400_000;

/** Rows on one page of a filter list before it paginates into `-2.md`. */
export const ROWS_PER_PAGE = 400;

/** The line carrying the timestamp, matched so a re-render can tell a real
 *  change from a change of clock. */
const UPDATED_LINE = /^_Last updated:.*$/m;

const GENERATED_NOTICE =
  '<!-- Generated by .github/scripts/render.mjs. Do not edit by hand: the next hourly run overwrites it. -->';

/** One row. `↳` repeats the company above it, the way these lists always have. */
function row(job, now, previousCompany, showAge) {
  const days = ageInDays(job.updatedAt, now);
  // `🆕` is the one marker derived from the clock, so it is a README marker
  // only: on a filter page it would rewrite rows on a day nothing happened,
  // and the page is sorted newest-first with a date in the last column, which
  // says the same thing without moving.
  const mark = markers(job, showAge ? days : null);
  const name = job.companyLabel || job.company || '';
  const company = name && name === previousCompany ? '↳' : `<strong>${escapeHtml(name || '—')}</strong>`;
  // The role links at the posting's own page on TrueInterview (`url`, which the
  // API answers with `/jobs/<id>`: one role, readable without an account, with
  // the ranking and tracking a click further in); the Apply cell links at the
  // employer's own form. Two links with two different jobs, rather than one
  // link that has to be both.
  const role = `${link(job.title || 'Untitled role', job.url)}${mark ? ` ${mark}` : ''}`;
  const apply = safeUrl(job.applyUrl) ? link('Apply', job.applyUrl) : '—';
  return [
    '<tr>',
    `<td>${company}</td>`,
    `<td>${role}</td>`,
    `<td>${locationLabel(job)}</td>`,
    `<td align="center">${apply}</td>`,
    `<td align="center">${showAge ? ageLabel(days) : postedLabel(job.updatedAt)}</td>`,
    '</tr>',
  ].join('\n');
}

/**
 * One table. Empty in means empty out — never a table with only a header.
 *
 * `showAge` is the difference between the README and a filter page. The README
 * is read the hour it is generated, so a relative age is the most useful thing
 * the last column can say; a filter page is bookmarked and shared, and a
 * relative age there is both stale on arrival and a guarantee that the file
 * rewrites itself every single day — see `postedLabel`.
 */
export function renderTable(jobs, now, { showAge = true } = {}) {
  if (!jobs.length) return '';
  const rows = [];
  let previousCompany = null;
  for (const job of jobs) {
    rows.push(row(job, now, previousCompany, showAge));
    previousCompany = job.companyLabel || job.company || '';
  }
  return [
    '<table>',
    '<thead>',
    `<tr><th>Company</th><th>Role</th><th>Location</th><th align="center">Apply</th><th align="center">${showAge ? 'Age' : 'Posted'}</th></tr>`,
    '</thead>',
    '<tbody>',
    ...rows,
    '</tbody>',
    '</table>',
  ].join('\n');
}

const count = (n) => n.toLocaleString('en-US');
const plural = (n, one, many) => (n === 1 ? one : many);

/**
 * One README section: the fresh table, the fold, and the way out to the rest.
 *
 * The caps are the point. Before them this section printed every row it had,
 * which on the new-grad list meant a README GitHub refused to finish rendering.
 * Now the section is a sample with a stated size and a link to the page that
 * holds all of it — and "Showing 25 of 958" is a more useful sentence than 958
 * rows a reader has to scroll past anyway.
 */
function renderSection(bucket, { now, featuredDays, backToTop, caps, trackPath }) {
  const heading = `${bucket.emoji} ${bucket.title}`;
  const { featured, older } = splitByFreshness(bucket.jobs, featuredDays, now);
  const shownFeatured = featured.slice(0, caps.featured);
  const shownOlder = older.slice(0, caps.fold);
  const total = bucket.jobs.length;
  const parts = [`## ${heading}`, '', `[Back to top](#${backToTop})`, ''];

  if (shownFeatured.length) {
    parts.push(renderTable(shownFeatured, now), '');
  } else {
    parts.push(
      `_Nothing posted in the last ${featuredDays} days. The older roles below are still open._`,
      '',
    );
  }
  if (shownOlder.length) {
    parts.push(
      '<details>',
      `<summary>Show ${count(shownOlder.length)} more ${bucket.title} ${plural(shownOlder.length, 'role', 'roles')} posted earlier</summary>`,
      '',
      renderTable(shownOlder, now),
      '',
      '</details>',
      '',
    );
  }
  const shown = shownFeatured.length + shownOlder.length;
  if (trackPath && total > shown) {
    parts.push(
      `**Showing ${count(shown)} of ${count(total)}.** ` +
        `[Every ${bucket.title} role, newest first →](${trackPath})`,
      '',
    );
  } else if (trackPath) {
    parts.push(`[All ${count(total)} on one page →](${trackPath})`, '');
  }
  return parts.join('\n');
}

/**
 * Who put the most roles up this week, in this file's region.
 *
 * The one block on the page that answers "where should I look TODAY". It is a
 * count of the rows already in the table rather than a ranking of employers —
 * a company that posted nine roles this week is not a better employer, it is a
 * company with nine open roles — and it says so, because a list of names with
 * numbers beside them is read as a league table unless it is labelled.
 */
function renderHiringNow(jobs, now, days, limit = 12) {
  const counts = new Map();
  for (const job of jobs) {
    const age = ageInDays(job.updatedAt, now);
    if (age === null || age > days) continue;
    const name = job.companyLabel || job.company;
    if (!name) continue;
    counts.set(name, (counts.get(name) ?? 0) + 1);
  }
  const ranked = [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .filter(([, n]) => n > 1)
    .slice(0, limit);
  if (ranked.length < 3) return '';
  return [
    `### 🔥 Posting the most this week`,
    '',
    ranked.map(([name, n]) => `**${escapeMarkdown(name)}** ${n}`).join(' &nbsp;·&nbsp; '),
    '',
    `<sub>Employers with more than one role posted in the last ${days} days, in this list. A count of ` +
      'open roles, not a ranking of employers.</sub>',
    '',
  ].join('\n');
}

/** The "browse by field" index, with the counts a reader scans first. */
function renderFieldIndex(buckets, total, noun) {
  const lines = [`### Browse ${count(total)} ${noun} by field`, ''];
  for (const bucket of buckets) {
    const heading = `${bucket.emoji} ${bucket.title}`;
    lines.push(`${bucket.emoji} **[${bucket.title}](#${anchorOf(heading)})** (${count(bucket.jobs.length)})`, '');
  }
  return lines.join('\n');
}

/** The emoji-and-title a filter is printed under, Markdown-safe. */
function trackLabel(track) {
  return `${track.emoji && track.emoji !== '•' ? `${track.emoji} ` : ''}${escapeMarkdown(track.title)}`;
}

/** One filter as an inline link: `🏛️ Big Tech (42)`. */
function trackLink(track, prefix, rows) {
  return `[${trackLabel(track)} (${count(rows)})](${prefix}${track.path}.md)`;
}

/**
 * The filters block: one line per group, dividers between them.
 *
 * `limit` keeps the README's copy of this to the filters people use, with the
 * hub one click away carrying all of them. The hub passes `Infinity`.
 */
export function renderFilters(
  tracks,
  { prefix = 'lists/', limit = 10, hubPath = 'lists/README.md', countOf = (track) => track.jobs.length, scopeNote = '' } = {},
) {
  const groups = groupTracks(tracks).filter((group) => group.id !== 'field');
  if (!groups.length) return '';
  const lines = ['### Filters', ''];
  if (scopeNote) lines.push(`_${scopeNote}_`, '');
  let printed = 0;
  for (const group of groups) {
    // Counted in the SCOPE of the file this block is printed in. A README that
    // says "179 posted this week" three lines under a headline that says 170 is
    // a page arguing with itself, and the reader cannot tell which number is
    // about the list they are reading.
    const ordered = group.tracks
      .map((track) => ({ track, rows: countOf(track) }))
      .filter((entry) => entry.rows > 0)
      .sort((a, b) => b.rows - a.rows || a.track.title.localeCompare(b.track.title));
    if (!ordered.length) continue;
    const shown = ordered.slice(0, limit);
    const rest = ordered.length - shown.length;
    printed += 1;
    lines.push(
      `${group.emoji} **${group.title}** — ` +
        shown.map((entry) => trackLink(entry.track, prefix, entry.rows)).join(' · ') +
        (rest > 0 ? ` · [+${rest} more →](${hubPath})` : ''),
      '',
    );
  }
  if (!printed) return '';
  lines.push(`[**Every filter, with counts and what each one selects →**](${hubPath})`, '');
  return lines.join('\n');
}

/**
 * The generated block: the headline, the two indexes, the legend, the sections.
 *
 * `emptyNote` is not an edge case to tidy away. A list that renders nothing has
 * to say whether it found nothing or could not look, and this renderer is only
 * ever reached on a read that SUCCEEDED — the fetch step throws instead — so
 * "nothing matched" is the honest sentence here.
 */
export function renderListings({
  jobs,
  now,
  featuredDays,
  noun,
  backToTop,
  sourceNote,
  tracks = [],
  caps = { featured: 25, fold: 50 },
  fieldPathOf = () => null,
  headline = '',
  scope = null,
  freshDays = 7,
}) {
  const buckets = groupByCategory(jobs);
  // The timestamp lives INSIDE the block so this renderer owns it, and
  // `changedBeyondTimestamp` knows to ignore it when deciding whether a run
  // produced anything worth committing.
  const parts = [BLOCK_START, '', updatedLine(now), ''];

  if (!jobs.length) {
    parts.push(
      `_No ${noun} matched the filters on the last run. The catalog is refreshed continuously — check back within the hour._`,
      '',
      BLOCK_END,
    );
    return parts.join('\n');
  }

  if (headline) parts.push(headline, '');
  parts.push(renderFieldIndex(buckets, jobs.length, noun));
  const hiring = renderHiringNow(jobs, now, freshDays);
  if (hiring) parts.push('---', '', hiring);
  const inScope = scope?.rows ? new Set(scope.rows) : null;
  const filters = renderFilters(tracks, {
    countOf: inScope ? (track) => track.jobs.reduce((total, job) => total + (inScope.has(job) ? 1 : 0), 0) : undefined,
    scopeNote: scope?.label ? `Counts are ${noun} in ${scope.label}. Each page carries every region, under its own heading.` : '',
  });
  if (filters) parts.push('---', '', filters);
  parts.push(
    '---',
    '',
    '### Legend',
    '',
    '🆕 Posted in the last 3 days &nbsp;·&nbsp; 🌐 Remote &nbsp;·&nbsp; 🛂 The posting carries a work-authorisation restriction',
    '',
    `_${sourceNote}_`,
    '',
    '---',
    '',
  );
  for (const bucket of buckets) {
    parts.push(
      renderSection(bucket, { now, featuredDays, backToTop, caps, trackPath: fieldPathOf(bucket) }),
    );
  }
  parts.push(BLOCK_END);
  return parts.join('\n');
}

// ── filter pages ─────────────────────────────────────────────────────────────

function pagePath(base, page) {
  return page === 1 ? `${base}.md` : `${base}-${page}.md`;
}

function pager(base, page, pages) {
  if (pages <= 1) return '';
  const name = (n) => pagePath(base, n).split('/').pop();
  const links = [];
  if (page > 1) links.push(`[← Page ${page - 1}](${name(page - 1)})`);
  links.push(`Page ${page} of ${pages}`);
  if (page < pages) links.push(`[Page ${page + 1} →](${name(page + 1)})`);
  return `<sub>${links.join(' · ')}</sub>`;
}

/**
 * One filter's pages: every matching row, home region first, then elsewhere.
 *
 * Regions are SECTIONS rather than separate files. A reader who filtered to
 * "Quant trading" has already asked a narrow question, and answering it with
 * two files they have to find separately is worse than one page that says which
 * half is which. A section that spans a page boundary repeats its heading, so
 * page 3 still says what it is a list of.
 */
export function renderTrackPages(track, { now, sections, rowsPerPage = ROWS_PER_PAGE }) {
  const base = `lists/${track.path}`;
  // How far below `lists/` this page sits, so the links back up are right for
  // both `lists/remote.md` and `lists/company/big-tech.md`.
  const depth = track.path.split('/').length - 1;
  const toHub = `${'../'.repeat(depth)}README.md`;
  const toList = `${'../'.repeat(depth + 1)}README.md`;

  const flat = sections.flatMap((section) => section.jobs.map((job) => ({ section, job })));
  const chunks = [];
  for (let index = 0; index < flat.length; index += rowsPerPage) {
    chunks.push(flat.slice(index, index + rowsPerPage));
  }
  if (!chunks.length) chunks.push([]);

  const title = `${track.emoji && track.emoji !== '•' ? `${track.emoji} ` : ''}${escapeMarkdown(track.title)}`;
  const split = sections
    .filter((section) => section.jobs.length)
    .map((section) => `${count(section.jobs.length)} ${section.summary ?? `in ${section.title}`}`)
    .join(' · ');
  const files = {};
  chunks.forEach((chunk, index) => {
    const page = index + 1;
    const nav = pager(base, page, chunks.length);
    const parts = [
      GENERATED_NOTICE,
      '',
      `# ${title}`,
      '',
      `**${count(track.jobs.length)} open ${plural(track.jobs.length, 'role', 'roles')}.**` +
        (sections.length > 1 ? ` ${split}.` : '') +
        (track.blurb ? ` ${track.blurb}` : ''),
      '',
      `[← Every filter](${toHub}) · [← The full list](${toList})`,
      '',
    ];
    // The rule rides on page 1 only: it is reference material about the filter
    // as a whole, and repeating it above page 4 pushes the rows a reader paged
    // forward for off the top of the screen.
    if (page === 1) {
      parts.push(`> ${track.note}`, '');
      parts.push(
        '_Newest first. 🌐 Remote &nbsp;·&nbsp; 🛂 The posting carries a work-authorisation restriction._',
        '',
      );
    }
    if (nav) parts.push(nav, '');

    // One table per contiguous run of one region, so a page that straddles the
    // two draws two tables under two headings rather than one table with a
    // surprise in the middle — and page 3 still says which half it is showing.
    let run = [];
    let runSection = null;
    const flush = () => {
      if (!run.length) return;
      parts.push(`## ${runSection.title}`, '');
      if (runSection.note) parts.push(`_${runSection.note}_`, '');
      parts.push(renderTable(run, now, { showAge: false }), '');
      run = [];
    };
    for (const entry of chunk) {
      if (entry.section !== runSection) {
        flush();
        runSection = entry.section;
      }
      run.push(entry.job);
    }
    flush();

    if (!chunk.length) parts.push('_Nothing matched this filter on the last run._', '');
    if (nav) parts.push(nav, '');
    parts.push(`[← Every filter](${toHub}) · [Back to the full list](${toList})`, '');
    files[pagePath(base, page)] = parts.join('\n');
  });
  return files;
}

/**
 * `lists/README.md` — the hub: every filter, its count, and its rule.
 *
 * The one page that has to be legible to somebody who arrived from a search
 * engine with no idea what this repository is, so it opens with what the
 * filters ARE before it opens with a table of them.
 */
export function renderHub({ tracks, now, listName, noun, coverageNote, homeLabel }) {
  const groups = groupTracks(tracks);
  const body = [
    GENERATED_NOTICE,
    '',
    `# Filters`,
    '',
    `Every cut of the ${escapeMarkdown(listName)} list that has a page of its own. ` +
      'Each one says exactly what it selects — these are filters over facts already on the ' +
      'row, never a hand-picked list of roles somebody liked.',
    '',
    '[← Back to the list](../README.md)',
    '',
    updatedLine(now),
    '',
  ];
  if (coverageNote) body.push(`> ${coverageNote}`, '');

  body.push('## What is here', '');
  for (const group of groups) {
    body.push(
      `${group.emoji} **[${group.title}](#${anchorOf(`${group.emoji} ${group.title}`)})** — ${group.blurb} ` +
        `(${count(group.tracks.length)} ${plural(group.tracks.length, 'filter', 'filters')})`,
      '',
    );
  }

  for (const group of groups) {
    const ordered = [...group.tracks].sort((a, b) => b.jobs.length - a.jobs.length || a.title.localeCompare(b.title));
    body.push(
      '---',
      '',
      `## ${group.emoji} ${group.title}`,
      '',
      `${group.blurb}`,
      '',
      '| Filter | Open roles | What it selects |',
      '| :-- | --: | :-- |',
      ...ordered.map(
        (track) =>
          `| [${trackLabel(track)}](${track.path}.md) | ${count(track.jobs.length)} | ${escapeMarkdown(track.note)} |`,
      ),
      '',
    );
  }

  body.push(
    '---',
    '',
    '## How a filter is built',
    '',
    `Every row on every page above is the same row you would find in [the main list](../README.md) — ` +
      `these pages are cuts, not a second catalog. A filter page carries **both regions**: roles in ` +
      `${escapeMarkdown(homeLabel)} first, then everywhere else, under their own headings.`,
    '',
    `A filter with fewer than 5 open ${noun} does not get a page at all. It would appear for an hour ` +
      'and vanish on the next run, and every link anyone had shared with it would break.',
    '',
  );
  return body.join('\n');
}

/** Replaces the generated block in `existing`, keeping every hand-written line. */
export function replaceBlock(existing, block) {
  const start = existing.indexOf(BLOCK_START);
  const end = existing.indexOf(BLOCK_END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      'The listings markers are missing from the file. Restore BLOCK_START / BLOCK_END or delete the file and let the next run recreate it.',
    );
  }
  return existing.slice(0, start) + block + existing.slice(end + BLOCK_END.length);
}

/**
 * Whether two renderings differ in anything a reader would notice.
 *
 * The timestamp is excluded on purpose. Without this the workflow would commit
 * every hour whether or not a single role had changed, and a history where
 * every commit is "the clock moved" cannot be read for what it is for — when
 * this employer posted, when that one pulled the role.
 */
export function changedBeyondTimestamp(before, after) {
  const strip = (text) => String(text ?? '').replace(UPDATED_LINE, '');
  return strip(before) !== strip(after);
}

/** The `_Last updated:_` line, in UTC so two runs never disagree by a timezone. */
export function updatedLine(now) {
  const iso = new Date(now).toISOString().replace('T', ' ').slice(0, 16);
  return `_Last updated: ${iso} UTC_`;
}
